name: Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '0 1 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Execute
        run: dart main.dart

      - name: Format Dart
        run: dart format output/device_identifiers.dart

      - name: Format Kotlin
        run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.46.1/ktlint && chmod a+x ktlint
        run: ./ktlint -F output/DeviceIdentifiers.kt

      - name: Test
        run: dart test

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "content: update device database (CI)"
