name: Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '0 1 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Execute
        run: dart main.dart

      - name: Format
        run: dart format output/device_identifiers.dart

      - name: Test
        run: dart test

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update device database via CI
